name: 'artifacts cleanup'
# on:
#   schedule:
#     - cron: '0 1 * * *' # every night at 1 am UTC
on: 
    workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.FOR_WEBHOOKS_SECRET }}
          expire-in: 0days # Set this to 0 to delete all artifacts