name: Build build-environment Docker Image

on:
  push:
    branches: 
      - main
    paths:
      - ".github/workflows/build-environment.yml"
      - "environments/build-environment/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@releases/v4
      with:
        images: |
          ghcr.io/${{github.repository}}/build-environment
        tags: |
          type=raw,value=latest

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: environments/build-environment
        push: true
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
        
