name: HHLA Sky Safety Controller CI/CD

on:
  push:
    branches: [main]  

jobs:
  Building_and_Testing_32-bit:
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/${{github.repository}}/build-environment
    #   credentials:
    #     username: ${{github.actor}}
    #     password: ${{secrets.GITHUB_TOKEN}}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      - name: Setup Ubuntu
        run: |
          sudo apt update && sudo apt install -y \
          build-essential \
          cmake \
          build-essential \
          binutils \
          gcc-multilib \
          g++-multilib \
          gcovr \
          git

      # Configure the project using CMake
      - name: Configure with CMake
        run: |
          mkdir -p build
          cmake -S . -B build

      # Build the project
      - name: Build project
        run: |
          cmake --build build -j$(nproc --all)
      
      # Run tests using CTest without verbose output to reduce warnings
      - name: Run tests
        if: success()
        run: |
          ctest --test-dir build -j$(nproc --all) -C Debug

          
      # # Upload build directory as artifact for further jobs if needed
      # - name: Upload build artifact
      #   if: success()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build
      #     path: build
      

      # Create issue on failure
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Build Failed on ${{ github.repository }}"
          content-filepath: ./build-failure.txt
          labels: bug, build-failure

      
