name: HHLA Sky Safety Controller CI

on:
  push:
    branches: [main]  

jobs:
  Building:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{github.repository}}/build-environment
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      # Configure the project using CMake
      - name: Configure with CMake
        run: |
          mkdir build
          cmake -B ./build

      # Build the project
      - name: Build project
        run: |
          cmake --build ./build -j$(nproc --all)

      # Create issue on failure
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Build Failed on ${{ github.repository }}"
          content-filepath: ./build-failure.txt
          labels: bug, build-failure

  Testing:
    needs: Building
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      # Run tests using CTest
      - name: Run tests
        run: |
          ctest --test-dir ./build -j$(nproc --all) -C Debug -T test
