name: Release Creation 

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      toolchain:
        type: choice
        description: Select toolchain
        options:
          - stm32-gcc-toolchain
          - bxarm-toolchain
        default: 'stm32-gcc-toolchain'
      configuration:
        type: choice
        description: Select configuration
        options:
          - debug
          - release
        default: 'debug'
      run-linux-jobs:
        type: boolean
        required: true

jobs:
  Main-Workflow:
    uses: ./.github/workflows/main_CICD.yml
    with:
      toolchain: ${{ github.event_name == 'workflow_dispatch' && inputs.toolchain || 'bxarm-toolchain' }}
      configuration: 'release'
      run-linux-jobs: ${{ github.event_name == 'workflow_dispatch' && inputs.run-linux-jobs || true  }}

  GitHub-Package:
    runs-on: ubuntu-22.04
    needs: Main-Workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download ELF Artifact
        uses: actions/download-artifact@v4
        with:
          name: STM32-Microcontroller_Binary
          path: ./STM32-Microcontroller_Binary

      - name: Package Artifact 
        run: |
          mkdir -p release-packages
          mv STM32-Microcontroller_Binary/*.elf release-packages/
          cd release-packages
          tar -czvf stm32_project_${{ github.ref_name || 'latest' }}.tar.gz *.elf

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} $GITHUB_REF_NAME" \
            --generate-notes
