name: Release Creation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: "Enter the tag name (required for release creation)"
        required: true
      toolchain:
        type: choice
        description: "Select toolchain"
        options:
          - stm32-gcc-toolchain
          - bxarm-toolchain
        default: 'stm32-gcc-toolchain'
      configuration:
        type: choice
        description: "Select configuration"
        options:
          - debug
          - release
        default: 'debug'
      run-linux-jobs:
        type: boolean
        required: true

jobs:
  Main-Workflow:
    uses: ./.github/workflows/main_CICD.yml
    with:
      toolchain: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.toolchain || 'bxarm-toolchain' }}
      configuration: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.configuration || 'release' }}
      run-linux-jobs: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run-linux-jobs || true }}

  GitHub-Package:
    runs-on: ubuntu-22.04
    needs: Main-Workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create Tag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}

      - name: Download ELF Artifact
        uses: actions/download-artifact@v4
        with:
          name: STM32-Microcontroller_Binary
          path: ./STM32-Microcontroller_Binary

      - name: Package Artifact 
        run: |
          mkdir -p release-packages
          mv STM32-Microcontroller_Binary/*.elf release-packages/
          cd release-packages
          tar -czvf stm32_project_${{ github.event.inputs.tag_name || 'latest' }}.tar.gz *.elf

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} $tag" \
            --generate-notes
