name: Publish to GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      toolchain:
        type: choice
        description: Select toolchain for the build
        options:
          - bxarm-toolchain
          - stm32-gcc-toolchain
        default: bxarm-toolchain

jobs:
  Linux-Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

  Target-Build:
    name: ${{ inputs.toolchain == 'stm32-gcc-toolchain' && 'STM32-GCC' || 'BXARM'}}
    uses: ./.github/workflows/reusable_build.yml
    with:
      toolchain: ${{ github.event.inputs.toolchain || 'bxarm-toolchain' }}
      configuration: release
    
  Download-artifacts:
    runs-on: ubuntu-22.04

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: STM32-Microcontroller_Binary
          path: mcu_test_proj/build/${{github.event.inputs.toolchain}}-release/*.elf

      - name: Package Artifact
        run: |
          mkdir -p release-packages
          mv STM32-Microcontroller_Binary release-packages/
          cd release-packages
          tar -czvf stm32_project_${{ github.event.release.tag_name || 'latest' }}.tar.gz STM32-Microcontroller_Binary

      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: stm32_project_${{ github.event.release.tag_name || 'latest' }}
          path: release-packages/stm32_project_${{ github.event.release.tag_name || 'latest' }}.tar.gz
