name: HHLA Sky SC - Target HW Build and Test

on: 
  workflow_run:
    workflows: ["HHLA Sky SC - CI/CD Main"]
    types:
      - completed
  
  # pull_request:
  #   branches: 
  #     - main

  workflow_dispatch:
    inputs:
        toolchain:
          type: choice
          description: Select toolchain
          options:
          - stm32-gcc-toolchain
          - bxarm-toolchain
        configuration:
          type: choice
          description: Select toolchain
          options:
            - debug
            - release
          default: 'debug'

jobs:
  Build_and_test_target_HW:
    name: "Build and test for/on HW"
    runs-on: [self-hosted, linux]
    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch')}}
    steps:
      - name: Setup
        run: |
          echo "Starting build for target HW!"
  
  Build:
    name: ${{ inputs.toolchain == 'stm32-gcc-toolchain' && 'STM32-GCC' || 'BXARM'}}
    uses: ./.github/workflows/reusable_build.yml
    with: 
      toolchain: ${{ github.event_name == 'workflow_dispatch' && inputs.toolchain || 'bxarm-toolchain'}}
      configuration: ${{ github.event_name == 'workflow_dispatch' && inputs.configuration || 'release'}} # Maybe relase\debug
    needs: 'Build_and_test_target_HW'

  Deploy:
    name: ${{ inputs.toolchain == 'stm32-gcc-toolchain' && 'STM32-GCC' || 'BXARM'}}
    uses: ./.github/workflows/reusable_deploy_and_test.yml
    needs: Build