name: HHLA Sky SC - CI/CD Main

on: 
  pull_request:
    branches: main

jobs:
  check_skip_flags:
    name: Check skip flags
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
    steps:
      - name: Get repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"
  build:
    name: "Build - Commit: ${{ github.event.workflow_run.head_commit.message }}"
    runs-on: ubuntu-22.04
    needs: check_skip_flags
    if: ${{ !contains(needs.check_skip_flags.outputs.head-commit-message, '#skip-main'))}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.ref }}

      - name: Setup Ubuntu
        run: |
          sudo apt update && sudo apt install -y \
          build-essential \
          cmake \
          binutils \
          gcc-multilib \
          g++-multilib \
          gcovr \
          git

      # Configure the project using CMake
      - name: Configure with CMake
        run: |
          mkdir -p build
          cmake -S . -B build

      # Build the project
      - name: Build project
        run: |
          cmake --build build -j$(nproc --all)

      # Upload build directory as artifact for testing job
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

      # Create issue on failure
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Build Failed"
          content-filepath: ./build-failure.txt
          labels: bug, build-failure

  test:
    name: "Test Project"
    runs-on: ubuntu-22.04
    needs: build  # Ensures test job runs after build job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # Download build artifact from build job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      # Grant execute permissions to test binaries
      - name: Grant execute permissions to test binaries
        run: chmod +x build/tests/*

      # Run tests using CTest
      - name: Run tests
        run: |
          ctest --test-dir build -j$(nproc --all) -C Debug

      # Create issue on failure
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Test Failed"
          content-filepath: ./test-failure.txt
          labels: bug, test-failure
