name: HHLA Sky SC - CI/CD Main

on: 
  pull_request:
    branches: 
      - main
  workflow_dispatch:
      
jobs:
  build:
    name: "Build Main CI/CD"
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Ubuntu
        run: |
          sudo apt update && sudo apt install -y \
          build-essential \
          cmake \
          binutils \
          gcc-multilib \
          g++-multilib \
          gcovr \
          git

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Configure the project using CMake
      - name: Configure with CMake
        run: |
          mkdir -p build
          cmake -S . -B build

      # Build the project
      - name: Build project
        run: |
          cmake --build build -j$(nproc --all)

      # Upload build directory as artifact for testing job
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

      # Create issue on failure
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Build Failed"
          content-filepath: ./build-failure.txt
          labels: bug, build-failure

  test:
    name: "Test Main CI/CD"
    runs-on: ubuntu-22.04
    needs: build  # Ensures test job runs after build job

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4
      #   with:
      #     submodules: recursive

      # Download build artifact from build job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      # Grant execute permissions to test binaries
      - name: Grant execute permissions to test binaries
        run: chmod +x build/tests/*

      # Run tests using CTest
      - name: Run tests
        run: |
          ctest --test-dir build -j$(nproc --all) -C Debug

      # Create issue on failure
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Test Failed"
          content-filepath: ./test-failure.txt
          labels: bug, test-failure
