name: HHLA Sky SC - CI/CD

on: 
  pull_request:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      toolchain:
        type: choice
        description: Select toolchain
        options:
          - stm32-gcc-toolchain
          - bxarm-toolchain
        default: 'stm32-gcc-toolchain'
      configuration:
        type: choice
        description: Select configuration
        options:
          - debug
          - release
        default: 'debug'
      run-linux-jobs:
        type: boolean
        required: true
      run-HITL-tests-jobs:
        type: boolean
        required: true
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      configuration:
        required: true
        type: string
      run-linux-jobs:
        required: true
        type: boolean 

jobs:
  Linux-Build:
    if: ${{ github.event_name == 'pull_request' || inputs.run-linux-jobs == true }}
    name: Linux-Build
    uses: ./.github/workflows/reusable_linux_build.yml
    with:
      run-linux-jobs: ${{ github.event_name == 'pull_request' || inputs.run-linux-jobs == true }}

  Linux-Unit_Test:
    if: ${{github.event_name == 'pull_request' || inputs.run-linux-jobs == true}}
    uses: ./.github/workflows/reusable_linux_unit_test.yml
    needs: Linux-Build
    with:
      run-linux-jobs: ${{ github.event_name == 'pull_request' || inputs.run-linux-jobs == true }}

  Target-Build:
    name: ${{ inputs.toolchain == 'stm32-gcc-toolchain' && 'STM32-GCC' || 'BXARM'}}
    uses: ./.github/workflows/reusable_build.yml
    with: 
      toolchain: ${{ github.event_name == 'workflow_dispatch' && inputs.toolchain || 'bxarm-toolchain'}}
      configuration: ${{ github.event_name == 'workflow_dispatch' && inputs.configuration || 'release'}}
    needs: Linux-Unit_Test
    if: |
      always()
      && !contains(needs.*.result, 'failure')
      && !contains(needs.*.result, 'cancelled')

  Target-Deploy:
    name: ${{ inputs.toolchain == 'stm32-gcc-toolchain' && 'STM32-GCC' || 'BXARM'}}
    uses: ./.github/workflows/reusable_deploy_and_test.yml
    needs: Target-Build
    if: |
      always()
      && contains(needs.*.result, 'success')
