name: Reusable deploy and test

on:
  workflow_call:

jobs:
  Target-Deploy_firmware:
    runs-on: [self-hosted, linux]
    steps:
      - name: Download ELF
        uses: actions/download-artifact@v4
        with:
          name: STM32-Microcontroller_Binary
          path: ./

      - name: Flash to MCU and test
        run: |
          ${HOME}/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin/STM32_Programmer_CLI -c port=SWD -d mcu_test_proj.elf -g

