name: Reusable Linux Build

on:
  workflow_call:
    inputs:
      run-linux-jobs:
        required: true
        type: boolean

jobs:
  Linux-Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Ubuntu
        run: |
          sudo apt update && sudo apt install -y \
          build-essential \
          cmake \
          binutils \
          gcc-multilib \
          g++-multilib \
          gcovr \
          git

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.ref }}

      - name: Configure with CMake
        run: |
          mkdir -p build
          cmake -S . -B build

      - name: Build project
        run: |
          cmake --build build -j$(nproc --all)

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Build Failed"
          content-filepath: ./build-failure.txt
          labels: bug, build-failure
