name: Reusable Linux Unit Test

on:
  workflow_call:
    inputs:
      run-linux-jobs:
        required: true
        type: boolean

jobs:
  Linux-Unit_Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Linux-build
          path: ./build

      - name: Grant execute permissions to test binaries
        run: chmod +x build/tests/*

      - name: Run tests
        run: |
          mkdir -p test-results
          ctest --test-dir build -j$(nproc --all) -C Debug --output-log test-results/test-log.txt

      - name: Save Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test_Results
          path: ./test-results
        
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Test Failed"
          content-filepath: ./test-failure.txt
          labels: bug, test-failure
