name: Build STM32 Project

on:
  workflow_run:
    workflows: ["HHLA Sky Safety Controller CI/CD"]
    types:
      - completed

jobs:
  Building_for_microcontroller:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: ghcr.io/${{github.repository}}/build-environment
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      - name: Set up ARM GCC Toolchain
        run: |
          PATH=$(pwd)/tools/bin:$PATH
          LD_LIBRARY_PATH=$(pwd)/tools/lib:$LD_LIBRARY_PATH   
          
      - name: Compile STM32 Project
        run: |
          cd Debug
          make clean
          make all      

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: STM32-Microcontroller_Binary
          path: ./*.elf
      
      
      
