name: Build STM32 Project

on:
  workflow_run:
    workflows: ["HHLA Sky Safety Controller CI/CD"]
    types:
      - completed

jobs:
  Building_for_microcontroller:
    name: "Build STM32 Project - Commit: ${{ github.event.workflow_run.head_commit.message }}"
    runs-on: [ self-hosted, linux ]
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (contains(github.event.head_commit.message, '#build gcc-arm')) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      - name: Verify Active Branch
        run: |
          echo "Checked out branch:"
          git branch --show-current
          echo "Remote branches:"
          git branch -r

      - name: Set up ARM GCC Toolchain and Compile STM32 Project
        run: |
          cd mcu_test_proj
          PATH=$(pwd)/tools/gcc/bin:$PATH
          LD_LIBRARY_PATH=$(pwd)/tools/gcc/lib:$LD_LIBRARY_PATH
          rm -rf build
          cmake . --preset=gcc-debug
          cmake --build --preset=gcc-debug

      - name: Flash to MCU and test
        run: |
          cd mcu_test_proj/build/gcc-debug
          ${HOME}/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin/STM32_Programmer_CLI -c port=SWD -d mcu_test_proj.elf -g

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: STM32-Microcontroller_Binary
          path: mcu_test_proj/Debug/*.elf

      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Building for microcontroller failed"
          content-filepath: ./build-failure.txt
          labels: bug, build-failure
