name: Build STM32 Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Building_and_Testing_32-bit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{github.repository}}/build-environment
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      - name: Set up ARM GCC Toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi

      - name: Compile STM32 Project
        run: |
          cd safety_controller/safety_controller_MC3
          make clean
          make

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: STM32-Build
          path: STM32-Build.tar.gz
