name: Build STM32 Project

on:
  workflow_run:
    workflows: ["HHLA Sky Safety Controller CI/CD"]
    types:
      - completed

jobs:
  Building_for_microcontroller:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # container:
    #   image: ghcr.io/${{github.repository}}/build-environment
    #   credentials:
    #     username: ${{github.actor}}
    #     password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      - name: Set up ARM GCC Toolchain and Compile STM32 Project
        run: |
          PATH=$(pwd)/tools/gcc/bin:$PATH
          LD_LIBRARY_PATH=$(pwd)/tools/gcc/lib:$LD_LIBRARY_PATH
          cd mcu_test_proj/Debug
          make clean
          make all
      - name: Flash to MCU and test
        run: |
          cd mcu_test_proj/Debug
          $(HOME)/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin/STM32_Programmer_CLI -c port=SWD -d test_elfs/blink.elf -g
      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: STM32-Microcontroller_Binary
          path: mcu_test_proj/Debug/*.elf
      
      
      
